apiVersion: v11
kind: Service
metadata:
  name: demo-service

spec:
  ports: 
  - name: demo-service 
    port: 8080
    targetPort: 8080
  
  selector: 
    app: demo-app

  type: LoadBalancer 

  kubectl expose webapp --type=NodePort --targerPort=80 --