apiVersion: v11
kind: Service
metadata:
  name: Karthik

spec: with carg
  ports: 
  - name: Vaishu 
    port: 8080
    targetPort: 8080
  
  selector: 
    app: demo-app

  type: LoadBalancer 

  kubectl expose webapp --type=NodePort --targerPort=80 --